gcs_bucket_01   = "04292021-gcs-bucket-0112"
gcp_project     = "encryptiun-devel"
gce_instance_01 = "analysis-vm-lnx-01"
machine_type    = "n1-standard-1"
zone            = "us-east4-a"
image_family    = "centos-cloud/centos-7"